// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.Shop.Coupons.Database;

#nullable disable

namespace Service.Shop.Coupons.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230913171643_SeedCoupon")]
    partial class SeedCoupon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Service.Shop.Coupons.Model.CouponModel", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("double");

                    b.Property<double>("MinDiscount")
                        .HasColumnType("double");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "EYR463#",
                            DiscountAmount = 30.0,
                            MinDiscount = 50.0
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "RT63#",
                            DiscountAmount = 30.0,
                            MinDiscount = 90.0
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "E763#",
                            DiscountAmount = 30.0,
                            MinDiscount = 20.0
                        },
                        new
                        {
                            CouponId = 4,
                            CouponCode = "E763748",
                            DiscountAmount = 30.0,
                            MinDiscount = 800.0
                        },
                        new
                        {
                            CouponId = 5,
                            CouponCode = "DU7448",
                            DiscountAmount = 30.0,
                            MinDiscount = 500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
